on:
  push:
  workflow_dispatch:

jobs:
  cleanup-images:
    runs-on: ubuntu-latest
    steps:
    - name: Delete untagged images
      uses: iaingalloway/devcontainers/.github/actions/delete-packages@main
      with:
        package-names: foo
        retention-threshold: 1 week ago UTC
        keep-at-least: 3
        dry-run: true
